"""
Language definitions for the ListeKolay file explorer application.
"""

# Import search translations
from search_translations import search_translations

# Import language dictionaries from new_languages
try:
    from new_languages import de_dict, fr_dict, ru_dict, es_dict, it_dict, fa_dict, ur_dict, hi_dict, zh_dict, ja_dict
except ImportError:
    # If module is not in the path, try relative import from current directory
    try:
        from attached_assets.new_languages import de_dict, fr_dict, ru_dict, es_dict, it_dict, fa_dict, ur_dict, hi_dict, zh_dict, ja_dict
    except ImportError:
        # Define empty dictionaries if imports fail
        de_dict = {}
        fr_dict = {}
        ru_dict = {}
        es_dict = {}
        it_dict = {}
        fa_dict = {}
        ur_dict = {}
        hi_dict = {}
        zh_dict = {}
        ja_dict = {}

def load_translations():
    """
    Load all translation dictionaries for the application.
    Returns a nested dictionary with language codes as keys.
    """
    # Define Turkish translations (base language)
    tr_dict = {
        "theme_settings": "Tema:",
        "light_mode": "Açık mod",
        "dark_mode": "Koyu mod",
        "open_file": "Dosyayı Aç",
        "open_file_location": "Dosya Konumunu Aç",
        "copy_filename": "Dosya Adını Kopyala",
        "copy_filepath": "Dosya Yolunu Kopyala",
        "select_folder": "📁 Klasör Seç",
        "no_folder_selected": "Henüz bir klasör seçilmedi",
        "start": "▶️ Başlat",
        "apply_filter": "🔍 Filtreyi Uygula",
        "cancel": "⏹️ İptal",
        "cancelling": "⏹️ İptal Ediliyor...",
        "exit": "✖️ Kapat",
        "select_all": "Tümünü Seç",
        "clear_all": "Temizle",
        "all_files_tip": "Tüm dosyalar uzantılarına bakılmaksızın listelenecek.",
        "filter_tip": "Filtreleme seçenekleri etkin, sadece seçilen uzantılara sahip dosyalar gösterilecek.",
        "calculating_statistics": "İstatistikler hesaplanıyor...",
        "loading_file_list": "Dosya listesi yükleniyor...",
        "tooltip_select": "Dosya listesi oluşturmak için bir klasör seçin",
        "tooltip_start": "Dosya listesini oluştur ve dışa aktar",
        "tooltip_apply": "Seçilen uzantılara göre dosyaları filtrele",
        "tooltip_cancel": "Devam eden işlemi iptal et",
        "tooltip_exit": "Uygulamayı kapat",
        "language": "Dil / Language",
        "view_mode_list": "Listele",
        "view_mode_preview": "Ön İzleme",
        "tooltip_list_view": "Dosyaları liste görünümünde göster",
        "tooltip_preview_view": "Dosyaları önizleme görünümünde göster",
        "files_and_previews": "Dosyalar ve Önizlemeler",
        "search_files": "Dosya ara...",
        "preview_mode_active": "Önizleme modu etkin",
        "loading_preview": "Önizlemeler yükleniyor...",
        "no_preview_available": "Önizlenebilir dosya bulunamadı",
        "preview_file": "Dosyayı Önizle",
        "open_file": "Dosyayı Aç",
        "open_file_location": "Dosya Konumunu Aç",
        "error_open_file": "Dosya açılırken bir hata oluştu",
        "error_open_location": "Dosya konumu açılırken bir hata oluştu",
        "error_open_url": "URL açılırken bir hata oluştu",
        "extension_not_found": "Uzantısı bulunamadı",
        "settings": "Ayarlar",
        "info": "Bilgi",
        "files_filtering": "Dosyalar filtreleniyor, lütfen bekleyin...",
        "files_gathering": "Dosyalar toplanıyor, lütfen bekleyin...",
        "files_loading": "Dosyalar Yükleniyor...",
        "filter_applying": "Filtre uygulanıyor...",
        "filter_cancelled": "Filtreleme işlemi iptal edildi",
        "excel_created": "Excel dosyası başarıyla oluşturuldu...",
        "error_occurred": "Bir hata oluştu: {0}",
        "error": "Hata",
        "ready": "Hazır",
        "operation_cancelled": "İşlem İptal Edildi",
        "file_processed": "İşlenen dosya: {0}/{1} • {2}",
        "prev_page": "Önceki",
        "next_page": "Sonraki",
        "page": "Sayfa",
        "processing": "İşleniyor: %{0:.1f}",
        "folder_loading": "Klasör yükleniyor...",
        "loading_subfolders": "Alt klasörler yükleniyor...",
        "folder_loaded_status": "📁 Klasör içeriği yüklendi. Liste oluşturmak için \"Başlat\" butonuna tıklayın.",
        "create_list_time": "🕒 Liste Oluşturulma Zamanı: {0}",
        "select_folder_first": "Lütfen önce bir klasör seçin!",
        "text_file_error": "Metin dosyası oluşturulamadı: {0}",
        "start_processing": "▶️ Liste oluşturuluyor...",
        "confirm_exit_title": "Çıkış",
        "confirm_exit_message": "Programdan çıkmak istediğinize emin misiniz?",
        "no_files_found": "Seçilen klasörde dosya bulunamadı.",
        "files_loaded_message": "{0} dosya yüklendi.",
        "files_filtered_message": "{0} dosya filtrelendi.",
        "filter_saved_message": "Filtreleme ayarları kaydedildi. Bir klasör seçtiğinizde uygulanacak.",
        "app_title": "ListeKolay - Dosya Listesi Oluşturucu",
        "app_subtitle": "Klasörlerinizdeki dosyaları hızlıca listeyin.",
        "full_window_title": "ListeKolay - Dosya Listesi Oluşturucu",
        "statistics_header": "İstatistikler",
        "total_files_label": "Toplam Dosya:",
        "folder_count_label": "Klasör Sayısı:",
        "total_size_label": "Toplam Boyut:",
        "tips_header": "İpuçları",
        "settings_header": "Ayarlar",
        "operation_status": "İşlem Durumu",
        "subfolders_label": "Alt Klasörler:",
        "include_label": "Dahil Et",
        "list_format_label": "Liste Formatı:",
        "save_location_label": "Kaydetme Yeri:",
        "desktop_label": "Masaüstü",
        "sort_criteria_label": "Sıralama Ölçütü:",
        "text_format_info": "Metin dosyası formatı",
        "excel_format_info": "Excel çalışma kitabı formatı",
        "word_format_info": "Word belgesi formatı",
        "html_format_info": "Web sayfası formatı",
        "filter_label": "Filtrele",
        "kategori_header": "Kategoriler",
        "extensions_header": "Dosya Uzantıları",
        "tip_1": "Alt klasör kutusunu işaretleyerek tüm alt dizinlerdeki dosyaları tarayabilirsiniz.",
        "tip_3": "Dosyaları isim, boyut veya uzantıya göre sıralayabilirsiniz.",
        "tip_4": "Oluşturulan listeler varsayılan olarak program klasörüne kaydedilir.",
        "tip_5": "Masaüstü seçeneğiyle dosyaları doğrudan masaüstüne kaydedebilirsiniz.",
        "tip_6": "İşlemi durdurmak için İptal düğmesini kullanın.",
        "tip_preview_formats": "PDF, JPG, PNG, GIF, PSD, AI, EPS dosyaları ön izleme özelliğine sahiptir.",
        "preview_file": "Dosyayı Önizle",
        "preview_window_title": "Dosya Önizleme",
        "preview_not_supported": "Bu dosya türü için önizleme desteklenmiyor.",
        "preview_error": "Dosya önizleme sırasında bir hata oluştu.",
        "file_list_section": "Dosyalar ve Önizlemeler",
        "list_view": "Listele",
        "preview_view": "Ön İzleme",
        "view_mode": "Görünüm Modu:",
        "preview_mode_active": "Ön izleme modu aktif",
        "no_preview_available": "Önizleme Yok",
        "loading_preview": "Önizleme yükleniyor...",
        "all_files": "Tüm Dosyalar",
        "all_files_filter": "Tüm Dosyalar",
        "image_files": "Resim Dosyaları",
        "audio_files": "Ses Dosyaları",
        "video_files": "Video Dosyaları",
        "document_files": "Doküman Dosyaları",
        "compressed_files": "Sıkıştırılmış Dosyalar",
        "executable_files": "Çalıştırılabilir Dosyalar",
        "yes": "Evet",
        "no": "Hayır",
        "excel_success": "Excel dosyası başarıyla oluşturuldu",
        "word_success": "Word belgesi başarıyla oluşturuldu",
        "html_success": "HTML dosyası başarıyla oluşturuldu",
        "text_success": "Metin dosyası başarıyla oluşturuldu",
        "open_file_title": "Dosyayı Aç",
        "open_file_message": "Dosyayı açmak istiyor musunuz?",
        "rename_file": "Dosyayı Yeniden Adlandır",
        "enter_new_filename": "Yeni dosya adını girin:",
        "warning": "Uyarı",
        "file_already_exists_override": "Bu isimde bir dosya zaten var. Üzerine yazmak istiyor musunuz?",
        "irreversible_action": "DİKKAT: Bu işlem geri alınamaz!",
        "confirm_continue": "Devam etmek istiyor musunuz?",
        "operation_complete": "İşlem Tamamlandı",
        "file_renamed_successfully": "Dosya başarıyla yeniden adlandırıldı:",
        "file_renamed": "Dosya yeniden adlandırıldı",
        "renaming_file": "Dosya yeniden adlandırılıyor...",
        "rename_error": "Yeniden Adlandırma Hatası",
        "no_files_to_select": "Seçilecek dosya yok.",
        "select_single_file": "Lütfen yalnızca bir dosya seçin.",
        "selection_error": "Seçim Hatası"
        "irreversible_action": "DİKKAT: Bu işlem geri alınamaz!\n\n'{old}' → '{new}'\n\nDevam etmek istiyor musunuz?",
        "file_renamed_successfully": "Dosya başarıyla yeniden adlandırıldı:\n'{old}' → '{new}'",

    }
    
    # Define English translations
    en_dict = {
        "theme_settings": "Theme:",
        "light_mode": "Light mode",
        "dark_mode": "Dark mode",
        "open_file": "Open file",
        "open_file_location": "Open file location",
        "copy_filename": "Copy filename",
        "copy_filepath": "Copy file path",
        "select_folder": "📁 Select Folder",
        "no_folder_selected": "No folder selected yet",
        "start": "▶️ Start",
        "apply_filter": "🔍 Apply Filter",
        "cancel": "⏹️ Cancel",
        "cancelling": "⏹️ Cancelling...",
        "exit": "✖️ Exit",
        "select_all": "Select All",
        "clear_all": "Clear All",
        "all_files_tip": "All files will be listed regardless of their extensions.",
        "filter_tip": "Filter options enabled, only files with selected extensions will be shown.",
        "calculating_statistics": "Calculating statistics...",
        "loading_file_list": "Loading file list...",
        "tooltip_select": "Select a folder to create file list",
        "tooltip_start": "Create and export file list",
        "tooltip_apply": "Filter files by selected extensions",
        "tooltip_cancel": "Cancel the ongoing operation",
        "tooltip_exit": "Close the application",
        "language": "Language",
        "view_mode_list": "List",
        "view_mode_preview": "Preview",
        "tooltip_list_view": "Show files in list view",
        "tooltip_preview_view": "Show files in preview mode",
        "files_and_previews": "Files and Previews",
        "search_files": "Search files...",
        "preview_mode_active": "Preview mode active",
        "loading_preview": "Loading previews...",
        "no_preview_available": "No preview available",
        "preview_file": "Preview File",
        "open_file": "Open File",
        "open_file_location": "Open File Location",
        "error_open_file": "Error opening file",
        "error_open_location": "Error opening file location",
        "error_open_url": "Error opening URL",
        "extension_not_found": "Extension not found",
        "settings": "Settings",
        "info": "Info",
        "files_filtering": "Filtering files, please wait...",
        "files_gathering": "Gathering files, please wait...",
        "files_loading": "Loading Files...",
        "filter_applying": "Applying filter...",
        "filter_cancelled": "Filter operation cancelled",
        "excel_created": "Excel file created successfully...",
        "error_occurred": "An error occurred: {0}",
        "error": "Error",
        "ready": "Ready",
        "operation_cancelled": "Operation Cancelled",
        "file_processed": "Processing file: {0}/{1} • {2}",
        "prev_page": "Previous",
        "next_page": "Next",
        "page": "Page",
        "processing": "Processing: %{0:.1f}",
        "folder_loading": "Loading folder...",
        "loading_subfolders": "Loading subfolders...",
        "folder_loaded_status": "📁 Folder content loaded. Click \"Start\" to create the list.",
        "create_list_time": "🕒 List Creation Time: {0}",
        "select_folder_first": "Please select a folder first!",
        "text_file_error": "Text file could not be created: {0}",
        "start_processing": "▶️ Creating list...",
        "confirm_exit_title": "Exit",
        "confirm_exit_message": "Are you sure you want to exit the program?",
        "no_files_found": "No files found in the selected folder.",
        "files_loaded_message": "{0} files loaded.",
        "files_filtered_message": "{0} files filtered.",
        "filter_saved_message": "Filter settings saved. Will be applied when you select a folder.",
        "app_title": "EasyLister - File List Generator",
        "app_subtitle": "Quickly list files in your folders.",
        "full_window_title": "EasyLister - File List Generator",
        "statistics_header": "Statistics",
        "total_files_label": "Total Files:",
        "folder_count_label": "Folder Count:",
        "total_size_label": "Total Size:",
        "tips_header": "Tips",
        "settings_header": "Settings",
        "operation_status": "Operation Status",
        "subfolders_label": "Subfolders:",
        "include_label": "Include",
        "list_format_label": "List Format:",
        "save_location_label": "Save Location:",
        "desktop_label": "Desktop",
        "sort_criteria_label": "Sort Criteria:",
        "text_format_info": "Text file format",
        "excel_format_info": "Excel workbook format",
        "word_format_info": "Word document format",
        "html_format_info": "Web page format",
        "filter_label": "Filter",
        "kategori_header": "Categories",
        "extensions_header": "File Extensions",
        "tip_1": "Check the subfolder box to scan all subdirectories.",
        "tip_3": "You can sort files by name, size, or extension.",
        "tip_4": "Lists are saved to the program folder by default.",
        "tip_5": "Save directly to desktop with the desktop option.",
        "tip_6": "Use the Cancel button to stop the process.",
        "tip_preview_formats": "PDF, JPG, PNG, GIF, PSD, AI, EPS files have preview capability.",
        "preview_file": "Preview File",
        "preview_window_title": "File Preview",
        "preview_not_supported": "Preview not supported for this file type.",
        "preview_error": "An error occurred during file preview.",
        "file_list_section": "Files and Previews",
        "list_view": "List",
        "preview_view": "Preview",
        "view_mode": "View Mode:",
        "preview_mode_active": "Preview mode active",
        "no_preview_available": "No Preview",
        "loading_preview": "Loading preview...",
        "all_files": "All Files",
        "all_files_filter": "All Files",
        "image_files": "Image Files",
        "audio_files": "Audio Files",
        "video_files": "Video Files",
        "document_files": "Document Files",
        "compressed_files": "Compressed Files",
        "executable_files": "Executable Files",
        "yes": "Yes",
        "no": "No",
        "excel_success": "Excel file successfully created",
        "word_success": "Word document successfully created",
        "html_success": "HTML file successfully created",
        "text_success": "Text file successfully created",
        "open_file_title": "Open File",
        "open_file_message": "Do you want to open the file?",
        "rename_file": "Rename File",
        "enter_new_filename": "Enter new file name:",
        "warning": "Warning",
        "file_already_exists_override": "A file with this name already exists. Do you want to overwrite it?",
        "irreversible_action": "WARNING: This action cannot be undone!",
        "confirm_continue": "Do you want to continue?",
        "operation_complete": "Operation Complete",
        "file_renamed_successfully": "File renamed successfully:",
        "file_renamed": "File renamed",
        "renaming_file": "Renaming file...",
        "rename_error": "Rename Error",
        "no_files_to_select": "No files available to select.",
        "select_single_file": "Please select only one file.",
        "selection_error": "Selection Error"
        "irreversible_action": "WARNING: This action is irreversible!\n\n'{old}' → '{new}'\n\nDo you want to continue?",
        "file_renamed_successfully": "File renamed successfully:\n'{old}' → '{new}'",

    }
    
    # Combine all translations into a single dictionary
    translations = {
        "tr": tr_dict,
        "en": en_dict,
        "de": de_dict,
        "fr": fr_dict,
        "ru": ru_dict,
        "es": es_dict,
        "it": it_dict,
        "fa": fa_dict,
        "ur": ur_dict,
        "hi": hi_dict,
        "zh": zh_dict,
        "ja": ja_dict
    }
    
    return translations

def get_language_options():
    """
    Returns a list of language options for the UI.
    Format: "Language Name (code)"
    """
    options = [
        "Türkçe (tr)",
        "English (en)",
        "Deutsch (de)",
        "Français (fr)",
        "Русский (ru)",
        "Español (es)",
        "Italiano (it)",
        "فارسی (fa)",
        "اردو (ur)",
        "हिन्दी (hi)",
        "中文 (zh)",
        "日本語 (ja)",
        "العربية (ar)"
    ]
    
    return options
