"""
New language dictionaries to be added to ListeKolay application.
"""

# German language dictionary
de_dict = {
    "open_file": "Datei öffnen",
    "open_file_location": "Dateipfad öffnen",
    "select_folder": "📁 Ordner auswählen",
    "no_folder_selected": "Noch kein Ordner ausgewählt",
    "start": "▶️ Start",
    "apply_filter": "🔍 Filter anwenden",
    "cancel": "⏹️ Abbrechen",
    "exit": "✖️ Beenden",
    "select_all": "Alle auswählen",
    "clear_all": "Alle löschen",
    "all_files_tip": "Alle Dateien werden unabhängig von der Erweiterung aufgelistet.",
    "filter_tip": "Filteroptionen aktiviert, nur Dateien mit ausgewählten Erweiterungen werden angezeigt.",
    "calculating_statistics": "Statistiken werden berechnet...",
    "loading_file_list": "Dateiliste wird geladen...",
    "tooltip_select": "Wählen Sie einen Ordner, um die Dateiliste zu erstellen",
    "tooltip_start": "Dateiliste erstellen und exportieren",
    "tooltip_apply": "Dateien nach ausgewählten Erweiterungen filtern",
    "tooltip_cancel": "Laufenden Vorgang abbrechen",
    "tooltip_exit": "Anwendung beenden",
    "language": "Sprache / Language",
    "settings": "Einstellungen",
    "info": "Info",
    "files_filtering": "Dateien werden gefiltert, bitte warten...",
    "files_gathering": "Dateien werden gesammelt, bitte warten...",
    "files_loading": "Dateien werden geladen...",
    "filter_applying": "Filter wird angewendet...",
    "filter_cancelled": "Filtervorgang abgebrochen",
    "excel_created": "Excel-Datei erfolgreich erstellt...",
    "error_occurred": "Ein Fehler ist aufgetreten: {0}",
    "error": "Fehler",
    "ready": "Bereit",
    "operation_cancelled": "Vorgang abgebrochen",
    "file_processed": "Datei wird verarbeitet: {0}/{1} • {2}",
    "processing": "Verarbeitung: %{0:.1f}",
    "folder_loading": "Ordner wird geladen...",
    "loading_subfolders": "Unterordner werden geladen...",
    "folder_loaded_status": "📁 Ordner geladen. Klicken Sie auf \"Start\", um die Liste zu erstellen.",
    "create_list_time": "🕒 Zeitpunkt der Listenerstellung: {0}",
    "select_folder_first": "Bitte wählen Sie zuerst einen Ordner aus!",
    "text_file_error": "Textdatei konnte nicht erstellt werden: {0}",
    "start_processing": "▶️ Liste wird erstellt...",
    "confirm_exit_title": "Beenden",
    "confirm_exit_message": "Sind Sie sicher, dass Sie das Programm beenden möchten?",
    "no_files_found": "Keine Dateien im ausgewählten Ordner gefunden.",
    "files_loaded_message": "{0} Dateien geladen.",
    "files_filtered_message": "{0} Dateien gefiltert.",
    "filter_saved_message": "Filtereinstellungen gespeichert. Wird angewendet, wenn ein Ordner ausgewählt wird.",
    "app_title": "EasyLister - Dateilisten-Generator",
    "app_subtitle": "Listen Sie schnell die Dateien in Ihren Ordnern auf.",
    "full_window_title": "EasyLister - Dateilisten-Generator",
    "statistics_header": "Statistiken",
    "total_files_label": "Gesamtzahl Dateien:",
    "folder_count_label": "Anzahl der Ordner:",
    "total_size_label": "Gesamtgröße:",
    "tips_header": "Tipps",
    "settings_header": "Einstellungen",
    "operation_status": "Betriebsstatus",
    "subfolders_label": "Unterordner einbeziehen:",
    "include_label": "Einbeziehen",
    "list_format_label": "Listenformat:",
    "save_location_label": "Speicherort:",
    "desktop_label": "Desktop",
    "sort_criteria_label": "Sortierkriterien:",
    "text_format_info": "Textdateiformat",
    "excel_format_info": "Excel-Arbeitsmappenformat",
    "word_format_info": "Word-Dokumentformat",
    "html_format_info": "Webseiten-Format",
    "filter_label": "Filter",
    "kategori_header": "Kategorien",
    "extensions_header": "Dateierweiterungen",
    "tip_1": "Kontrollkästchen für Unterordner aktivieren.",
    "tip_2": "Ausgabeformat auswählen.",
    "tip_3": "Sie können die Dateien sortieren.",
    "tip_4": "Listen werden im Programmordner gespeichert.",
    "tip_5": "Mit der Desktop-Option auf dem Desktop speichern.",
    "tip_6": "Verwenden Sie die Schaltfläche Abbrechen, um den Vorgang zu beenden.",
    "all_files": "Alle Dateien",
    "image_files": "Bilddateien",
    "audio_files": "Audiodateien",
    "video_files": "Videodateien",
    "text_files": "Textdateien",
    "program_files": "Programmdateien",
    "compressed_files": "Komprimierte Dateien",
    "document_files": "Dokumentdateien",
    "spreadsheet_files": "Tabellenkalkulationsdateien",
    "presentation_files": "Präsentationsdateien",
    "sort_name_asc": "Dateiname - Aufsteigend",
    "sort_name_desc": "Dateiname - Absteigend",
    "sort_ext_asc": "Dateierweiterung - Aufsteigend",
    "sort_ext_desc": "Dateierweiterung - Absteigend",
    "sort_size_asc": "Dateigröße - Aufsteigend",
    "sort_size_desc": "Dateigröße - Absteigend",
    "sort_dir_asc": "Dateiverzeichnis - Aufsteigend",
    "selected_folder": "Ausgewählter Ordner:",
    "file_list": "Dateiliste",
    "row_number": "Zeilennummer",
    "file_name": "Dateiname",
    "file_type": "Dateityp",
    "file_path": "Dateipfad",
    "file_size": "Dateigröße",
    "creation_date": "Erstellungsdatum",
    "modification_date": "Änderungsdatum",
    "file_extension": "Dateierweiterung",
    "creation_time": "Erstellungszeit:",
    "sorted_by": "Sortiert nach:",
    "excel_success": "Excel-Datei erfolgreich erstellt",
    "word_success": "Word-Dokument erfolgreich erstellt",
    "html_success": "HTML-Datei erfolgreich erstellt",
    "text_success": "Textdatei erfolgreich erstellt",
    "open_file_title": "Datei öffnen",
    "open_file_message": "Möchten Sie die Datei öffnen?",
    "yes": "Ja",
    "no": "Nein",
    "tooltip_subfolders": "Listet auch Dateien in Unterordnern auf",
    "tooltip_format": "Wählen Sie das Format, in dem Ihre Liste gespeichert wird",
    "tooltip_save_location": "Wählen Sie, wo Ihre Liste gespeichert werden soll",
    "tooltip_sort_criteria": "Wählen Sie, wie Dateien sortiert werden sollen",
    "tooltip_select_all": "Alle Dateierweiterungen auswählen",
    "tooltip_clear_all": "Alle Dateierweiterungsauswahlen löschen",
    "tooltip_file_category": "Klicken Sie, um Dateikategorien anzuzeigen",
    "tooltip_file_extension": "Wählen Sie Dateierweiterungen, die aufgelistet werden sollen",
    "tooltip_filter_apply": "Klicken Sie, um ausgewählte Filter anzuwenden",
    "tooltip_all_files": "Alle Dateierweiterungen auswählen/abwählen",
    "tooltip_category_expand": "Klicken Sie, um diese Kategorie zu erweitern/zu reduzieren",
    "tooltip_select_category": "Alle Erweiterungen in dieser Kategorie auswählen/abwählen",
    "select_all_category": "Alle in dieser Kategorie auswählen",
    "media_files": "Mediendateien (Audio & Video)",
    "code_files": "Code- & Webdateien",
    "design_files": "Designdateien",
    "game_files": "Spieldateien",
    "extension_search": "Suche:",
    "files_and_previews": "Dateien und Vorschauen",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}

# French language dictionary
fr_dict = {
    "open_file": "Ouvrir fichier",
    "open_file_location": "Ouvrir l'emplacement",
    "select_folder": "📁 Sélectionner dossier",
    "no_folder_selected": "Aucun dossier sélectionné",
    "start": "▶️ Démarrer",
    "apply_filter": "🔍 Appliquer filtre",
    "cancel": "⏹️ Annuler",
    "exit": "✖️ Quitter",
    "select_all": "Tout sélectionner",
    "clear_all": "Tout effacer",
    "all_files_tip": "Tous les fichiers seront listés indépendamment de leur extension.",
    "filter_tip": "Options de filtrage activées, seuls les fichiers avec les extensions sélectionnées seront affichés.",
    "calculating_statistics": "Calcul des statistiques...",
    "loading_file_list": "Chargement de la liste des fichiers...",
    "tooltip_select": "Sélectionnez un dossier pour générer la liste des fichiers",
    "tooltip_start": "Créer et exporter la liste des fichiers",
    "tooltip_apply": "Filtrer les fichiers par extensions sélectionnées",
    "tooltip_cancel": "Annuler l'opération en cours",
    "tooltip_exit": "Quitter l'application",
    "language": "Langue / Language",
    "settings": "Paramètres",
    "info": "Info",
    "files_filtering": "Filtrage des fichiers, veuillez patienter...",
    "files_gathering": "Collecte des fichiers, veuillez patienter...",
    "files_loading": "Chargement des fichiers...",
    "filter_applying": "Application du filtre...",
    "filter_cancelled": "Opération de filtrage annulée",
    "excel_created": "Fichier Excel créé avec succès...",
    "error_occurred": "Une erreur s'est produite: {0}",
    "error": "Erreur",
    "ready": "Prêt",
    "operation_cancelled": "Opération annulée",
    "file_processed": "Traitement du fichier: {0}/{1} • {2}",
    "processing": "Traitement: %{0:.1f}",
    "folder_loading": "Chargement du dossier...",
    "loading_subfolders": "Chargement des sous-dossiers...",
    "folder_loaded_status": "📁 Dossier chargé. Cliquez sur \"Démarrer\" pour générer la liste.",
    "create_list_time": "🕒 Heure de création de la liste: {0}",
    "select_folder_first": "Veuillez d'abord sélectionner un dossier!",
    "text_file_error": "Le fichier texte n'a pas pu être créé: {0}",
    "start_processing": "▶️ Création de la liste...",
    "confirm_exit_title": "Quitter",
    "confirm_exit_message": "Êtes-vous sûr de vouloir quitter le programme?",
    "no_files_found": "Aucun fichier trouvé dans le dossier sélectionné.",
    "files_loaded_message": "{0} fichiers chargés.",
    "files_filtered_message": "{0} fichiers filtrés.",
    "filter_saved_message": "Paramètres de filtrage enregistrés. Seront appliqués lors de la sélection d'un dossier.",
    "app_title": "ListeFacile - Générateur de liste de fichiers",
    "app_subtitle": "Listez rapidement les fichiers de vos dossiers.",
    "full_window_title": "ListeFacile - Générateur de liste de fichiers",
    "statistics_header": "Statistiques",
    "total_files_label": "Total des fichiers:",
    "folder_count_label": "Nombre de dossiers:",
    "total_size_label": "Taille totale:",
    "tips_header": "Conseils",
    "settings_header": "Paramètres",
    "operation_status": "État de l'opération",
    "subfolders_label": "Inclure les sous-dossiers:",
    "include_label": "Inclure",
    "list_format_label": "Format de la liste:",
    "save_location_label": "Emplacement de sauvegarde:",
    "desktop_label": "Bureau",
    "sort_criteria_label": "Critères de tri:",
    "text_format_info": "Format de fichier texte",
    "excel_format_info": "Format de classeur Excel",
    "word_format_info": "Format de document Word",
    "html_format_info": "Format de page Web",
    "filter_label": "Filtre",
    "kategori_header": "Catégories",
    "extensions_header": "Extensions de fichiers",
    "tip_1": "Cochez la case pour les sous-dossiers.",
    "tip_2": "Sélectionnez le format de sortie.",
    "tip_3": "Vous pouvez trier les fichiers.",
    "tip_4": "Les listes sont enregistrées dans le dossier du programme.",
    "tip_5": "Enregistrez sur le bureau avec l'option bureau.",
    "tip_6": "Utilisez le bouton Annuler pour arrêter le processus.",
    "all_files": "Tous les fichiers",
    "image_files": "Fichiers image",
    "audio_files": "Fichiers audio",
    "video_files": "Fichiers vidéo",
    "text_files": "Fichiers texte",
    "program_files": "Fichiers programme",
    "compressed_files": "Fichiers compressés",
    "document_files": "Fichiers document",
    "spreadsheet_files": "Fichiers tableur",
    "presentation_files": "Fichiers présentation",
    "sort_name_asc": "Nom de fichier - Croissant",
    "sort_name_desc": "Nom de fichier - Décroissant",
    "sort_ext_asc": "Extension de fichier - Croissant",
    "sort_ext_desc": "Extension de fichier - Décroissant",
    "sort_size_asc": "Taille de fichier - Croissant",
    "sort_size_desc": "Taille de fichier - Décroissant",
    "sort_dir_asc": "Répertoire de fichier - Croissant",
    "selected_folder": "Dossier sélectionné:",
    "file_list": "Liste des fichiers",
    "row_number": "N° de ligne",
    "file_name": "Nom du fichier",
    "file_type": "Type de fichier",
    "file_path": "Chemin du fichier",
    "file_size": "Taille du fichier",
    "creation_date": "Date de création",
    "modification_date": "Date de modification",
    "file_extension": "Extension de fichier",
    "creation_time": "Heure de création:",
    "sorted_by": "Trié par:",
    "excel_success": "Fichier Excel créé avec succès",
    "word_success": "Document Word créé avec succès",
    "html_success": "Fichier HTML créé avec succès",
    "text_success": "Fichier texte créé avec succès",
    "open_file_title": "Ouvrir le fichier",
    "open_file_message": "Voulez-vous ouvrir le fichier?",
    "yes": "Oui",
    "no": "Non",
    "tooltip_subfolders": "Liste également les fichiers dans les sous-dossiers",
    "tooltip_format": "Sélectionnez le format dans lequel votre liste sera enregistrée",
    "tooltip_save_location": "Sélectionnez où votre liste sera enregistrée",
    "tooltip_sort_criteria": "Sélectionnez comment les fichiers seront triés",
    "tooltip_select_all": "Sélectionner toutes les extensions de fichier",
    "tooltip_clear_all": "Effacer toutes les sélections d'extension de fichier",
    "tooltip_file_category": "Cliquez pour afficher les catégories de fichiers",
    "tooltip_file_extension": "Sélectionnez les extensions de fichier à lister",
    "tooltip_filter_apply": "Cliquez pour appliquer les filtres sélectionnés",
    "tooltip_all_files": "Sélectionner/Désélectionner toutes les extensions de fichier",
    "tooltip_category_expand": "Cliquez pour développer/réduire cette catégorie",
    "tooltip_select_category": "Sélectionner/Désélectionner toutes les extensions dans cette catégorie",
    "select_all_category": "Sélectionner tout dans cette catégorie",
    "media_files": "Fichiers média (Audio & Vidéo)",
    "code_files": "Fichiers code & web",
    "design_files": "Fichiers design",
    "game_files": "Fichiers jeu",
    "extension_search": "Recherche:",
    "cancelling": "⏹️ Annulation...",
    "view_mode_list": "Vue liste",
    "view_mode_preview": "Aperçu",
    "tooltip_list_view": "Afficher les fichiers en mode liste",
    "tooltip_preview_view": "Afficher les fichiers avec des vignettes d'aperçu",
    "search_files": "Rechercher des fichiers...",
    "preview_mode_active": "Mode aperçu actif",
    "loading_preview": "Chargement des aperçus...",
    "no_preview_available": "Aucun fichier prévisualisable trouvé",
    "preview_file": "Aperçu du fichier",
    "prev_page": "Précédent",
    "next_page": "Suivant",
    "page": "Page",
    "files_and_previews": "Fichiers et aperçus",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}

# Russian language dictionary
ru_dict = {
    "open_file": "Открыть файл",
    "open_file_location": "Открыть расположение файла",
    "select_folder": "📁 Выбрать папку",
    "no_folder_selected": "Папка еще не выбрана",
    "start": "▶️ Старт",
    "apply_filter": "🔍 Применить фильтр",
    "cancel": "⏹️ Отмена",
    "exit": "✖️ Выход",
    "select_all": "Выбрать все",
    "clear_all": "Очистить все",
    "all_files_tip": "Будут перечислены все файлы независимо от расширения.",
    "filter_tip": "Опции фильтрации включены, будут показаны только файлы с выбранными расширениями.",
    "calculating_statistics": "Расчет статистики...",
    "loading_file_list": "Загрузка списка файлов...",
    "tooltip_select": "Выберите папку для создания списка файлов",
    "tooltip_start": "Создать и экспортировать список файлов",
    "tooltip_apply": "Фильтровать файлы по выбранным расширениям",
    "tooltip_cancel": "Отменить текущую операцию",
    "tooltip_exit": "Выйти из приложения",
    "language": "Язык / Language",
    "settings": "Настройки",
    "info": "Информация",
    "files_filtering": "Фильтрация файлов, пожалуйста, подождите...",
    "files_gathering": "Сбор файлов, пожалуйста, подождите...",
    "files_loading": "Загрузка файлов...",
    "filter_applying": "Применение фильтра...",
    "filter_cancelled": "Операция фильтрации отменена",
    "excel_created": "Файл Excel успешно создан...",
    "error_occurred": "Произошла ошибка: {0}",
    "error": "Ошибка",
    "ready": "Готово",
    "operation_cancelled": "Операция отменена",
    "file_processed": "Обработка файла: {0}/{1} • {2}",
    "processing": "Обработка: %{0:.1f}",
    "folder_loading": "Загрузка папки...",
    "loading_subfolders": "Загрузка подпапок...",
    "folder_loaded_status": "📁 Содержимое папки загружено. Нажмите \"Старт\", чтобы создать список.",
    "create_list_time": "🕒 Время создания списка: {0}",
    "select_folder_first": "Пожалуйста, сначала выберите папку!",
    "text_file_error": "Текстовый файл не может быть создан: {0}",
    "start_processing": "▶️ Создание списка...",
    "confirm_exit_title": "Выход",
    "confirm_exit_message": "Вы уверены, что хотите выйти из программы?",
    "no_files_found": "Файлы в выбранной папке не найдены.",
    "files_loaded_message": "Загружено {0} файлов.",
    "files_filtered_message": "Отфильтровано {0} файлов.",
    "filter_saved_message": "Настройки фильтра сохранены. Будут применены при выборе папки.",
    "app_title": "СписокЛегко - Генератор списка файлов",
    "app_subtitle": "Быстро составляйте списки файлов в ваших папках.",
    "full_window_title": "СписокЛегко - Генератор списка файлов",
    "statistics_header": "Статистика",
    "total_files_label": "Всего файлов:",
    "folder_count_label": "Количество папок:",
    "total_size_label": "Общий размер:",
    "tips_header": "Советы",
    "settings_header": "Настройки",
    "operation_status": "Статус операции",
    "subfolders_label": "Включить подпапки:",
    "include_label": "Включить",
    "list_format_label": "Формат списка:",
    "save_location_label": "Место сохранения:",
    "desktop_label": "Рабочий стол",
    "sort_criteria_label": "Критерии сортировки:",
    "text_format_info": "Формат текстового файла",
    "excel_format_info": "Формат книги Excel",
    "word_format_info": "Формат документа Word",
    "html_format_info": "Формат веб-страницы",
    "filter_label": "Фильтр",
    "kategori_header": "Категории",
    "extensions_header": "Расширения файлов",
    "tip_1": "Отметьте флажок для подпапок.",
    "tip_2": "Выберите формат вывода.",
    "tip_3": "Вы можете сортировать файлы.",
    "tip_4": "Списки сохраняются в папке программы.",
    "tip_5": "Сохраняйте на рабочем столе с помощью опции рабочего стола.",
    "tip_6": "Используйте кнопку Отмена, чтобы остановить процесс.",
    "all_files": "Все файлы",
    "image_files": "Файлы изображений",
    "audio_files": "Аудио файлы",
    "video_files": "Видео файлы",
    "text_files": "Текстовые файлы",
    "program_files": "Программные файлы",
    "compressed_files": "Сжатые файлы",
    "document_files": "Документы",
    "spreadsheet_files": "Электронные таблицы",
    "presentation_files": "Презентации",
    "sort_name_asc": "Имя файла - По возрастанию",
    "sort_name_desc": "Имя файла - По убыванию",
    "sort_ext_asc": "Расширение файла - По возрастанию",
    "sort_ext_desc": "Расширение файла - По убыванию",
    "sort_size_asc": "Размер файла - По возрастанию",
    "sort_size_desc": "Размер файла - По убыванию",
    "sort_dir_asc": "Директория файлов - По возрастанию",
    "selected_folder": "Выбранная папка:",
    "file_list": "Список файлов",
    "row_number": "№ п/п",
    "file_name": "Имя файла",
    "file_type": "Тип файла",
    "file_path": "Путь к файлу",
    "file_size": "Размер файла",
    "creation_date": "Дата создания",
    "modification_date": "Дата изменения",
    "file_extension": "Расширение файла",
    "creation_time": "Время создания:",
    "sorted_by": "Отсортировано по:",
    "excel_success": "Файл Excel успешно создан",
    "word_success": "Документ Word успешно создан",
    "html_success": "HTML-файл успешно создан",
    "text_success": "Текстовый файл успешно создан",
    "open_file_title": "Открыть файл",
    "open_file_message": "Вы хотите открыть файл?",
    "yes": "Да",
    "no": "Нет",
    "tooltip_subfolders": "Также перечисляет файлы в подпапках",
    "tooltip_format": "Выберите формат, в котором будет сохранен ваш список",
    "tooltip_save_location": "Выберите, где будет сохранен ваш список",
    "tooltip_sort_criteria": "Выберите, как будут сортироваться файлы",
    "tooltip_select_all": "Выбрать все расширения файлов",
    "tooltip_clear_all": "Очистить все выбранные расширения файлов",
    "tooltip_file_category": "Нажмите, чтобы просмотреть категории файлов",
    "tooltip_file_extension": "Выберите расширения файлов для списка",
    "tooltip_filter_apply": "Нажмите, чтобы применить выбранные фильтры",
    "tooltip_all_files": "Выбрать/отменить выбор всех расширений файлов",
    "tooltip_category_expand": "Нажмите, чтобы развернуть/свернуть эту категорию",
    "tooltip_select_category": "Выбрать/отменить выбор всех расширений в этой категории",
    "select_all_category": "Выбрать все в этой категории",
    "media_files": "Медиа файлы (Аудио и Видео)",
    "code_files": "Файлы кода и web",
    "design_files": "Файлы дизайна",
    "game_files": "Игровые файлы",
    "extension_search": "Поиск:",
    "cancelling": "⏹️ Отмена...",
    "view_mode_list": "Список",
    "view_mode_preview": "Предпросмотр",
    "tooltip_list_view": "Показать файлы в виде списка",
    "tooltip_preview_view": "Показать файлы с миниатюрами предпросмотра",
    "search_files": "Поиск файлов...",
    "preview_mode_active": "Режим предпросмотра активен",
    "loading_preview": "Загрузка предпросмотров...",
    "no_preview_available": "Файлы для предпросмотра не найдены",
    "preview_file": "Предпросмотр файла",
    "prev_page": "Предыдущая",
    "next_page": "Следующая",
    "page": "Страница",
    "files_and_previews": "Файлы и предпросмотр",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}

# Spanish language dictionary
es_dict = {
    "open_file": "Abrir archivo",
    "open_file_location": "Abrir ubicación del archivo",
    "select_folder": "📁 Seleccionar carpeta",
    "no_folder_selected": "Ninguna carpeta seleccionada",
    "start": "▶️ Iniciar",
    "apply_filter": "🔍 Aplicar filtro",
    "cancel": "⏹️ Cancelar",
    "exit": "✖️ Salir",
    "select_all": "Seleccionar todo",
    "clear_all": "Borrar todo",
    "all_files_tip": "Se listarán todos los archivos independientemente de su extensión.",
    "filter_tip": "Opciones de filtrado habilitadas, solo se mostrarán archivos con las extensiones seleccionadas.",
    "calculating_statistics": "Calculando estadísticas...",
    "loading_file_list": "Cargando lista de archivos...",
    "tooltip_select": "Seleccione una carpeta para generar la lista de archivos",
    "tooltip_start": "Crear y exportar la lista de archivos",
    "tooltip_apply": "Filtrar archivos por extensiones seleccionadas",
    "tooltip_cancel": "Cancelar la operación en curso",
    "tooltip_exit": "Salir de la aplicación",
    "language": "Idioma / Language",
    "settings": "Configuración",
    "info": "Información",
    "files_filtering": "Filtrando archivos, por favor espere...",
    "files_gathering": "Recopilando archivos, por favor espere...",
    "files_loading": "Cargando archivos...",
    "filter_applying": "Aplicando filtro...",
    "filter_cancelled": "Operación de filtrado cancelada",
    "excel_created": "Archivo Excel creado con éxito...",
    "error_occurred": "Se ha producido un error: {0}",
    "error": "Error",
    "ready": "Listo",
    "operation_cancelled": "Operación cancelada",
    "file_processed": "Procesando archivo: {0}/{1} • {2}",
    "processing": "Procesando: %{0:.1f}",
    "folder_loading": "Cargando carpeta...",
    "loading_subfolders": "Cargando subcarpetas...",
    "folder_loaded_status": "📁 Contenido de la carpeta cargado. Haga clic en \"Iniciar\" para crear la lista.",
    "create_list_time": "🕒 Hora de creación de la lista: {0}",
    "select_folder_first": "¡Por favor, seleccione primero una carpeta!",
    "text_file_error": "No se pudo crear el archivo de texto: {0}",
    "start_processing": "▶️ Creando lista...",
    "confirm_exit_title": "Salir",
    "confirm_exit_message": "¿Está seguro de que desea salir del programa?",
    "no_files_found": "No se encontraron archivos en la carpeta seleccionada.",
    "files_loaded_message": "{0} archivos cargados.",
    "files_filtered_message": "{0} archivos filtrados.",
    "filter_saved_message": "Configuración de filtrado guardada. Se aplicará cuando seleccione una carpeta.",
    "app_title": "ListaFácil - Generador de listas de archivos",
    "app_subtitle": "Liste rápidamente los archivos en sus carpetas.",
    "full_window_title": "ListaFácil - Generador de listas de archivos",
    "statistics_header": "Estadísticas",
    "total_files_label": "Total de archivos:",
    "folder_count_label": "Número de carpetas:",
    "total_size_label": "Tamaño total:",
    "tips_header": "Consejos",
    "settings_header": "Configuración",
    "operation_status": "Estado de la operación",
    "subfolders_label": "Incluir subcarpetas:",
    "include_label": "Incluir",
    "list_format_label": "Formato de lista:",
    "save_location_label": "Ubicación de guardado:",
    "desktop_label": "Escritorio",
    "sort_criteria_label": "Criterio de ordenación:",
    "text_format_info": "Formato de archivo de texto",
    "excel_format_info": "Formato de libro de Excel",
    "word_format_info": "Formato de documento Word",
    "html_format_info": "Formato de página web",
    "filter_label": "Filtro",
    "kategori_header": "Categorías",
    "extensions_header": "Extensiones de archivo",
    "tip_1": "Marque la casilla para subcarpetas.",
    "tip_2": "Seleccione formato de salida.",
    "tip_3": "Puede ordenar los archivos.",
    "tip_4": "Las listas se guardan en la carpeta del programa.",
    "tip_5": "Guarde en el escritorio con la opción escritorio.",
    "tip_6": "Use el botón Cancelar para detener el proceso.",
    "all_files": "Todos los archivos",
    "image_files": "Archivos de imagen",
    "audio_files": "Archivos de audio",
    "video_files": "Archivos de video",
    "text_files": "Archivos de texto",
    "program_files": "Archivos de programa",
    "compressed_files": "Archivos comprimidos",
    "document_files": "Documentos",
    "spreadsheet_files": "Hojas de cálculo",
    "presentation_files": "Presentaciones",
    "sort_name_asc": "Nombre de archivo - Ascendente",
    "sort_name_desc": "Nombre de archivo - Descendente",
    "sort_ext_asc": "Extensión de archivo - Ascendente",
    "sort_ext_desc": "Extensión de archivo - Descendente",
    "sort_size_asc": "Tamaño de archivo - Ascendente",
    "sort_size_desc": "Tamaño de archivo - Descendente",
    "sort_dir_asc": "Directorio de archivo - Ascendente",
    "selected_folder": "Carpeta seleccionada:",
    "file_list": "Lista de archivos",
    "row_number": "Nº de fila",
    "file_name": "Nombre de archivo",
    "file_type": "Tipo de archivo",
    "file_path": "Ruta de archivo",
    "file_size": "Tamaño de archivo",
    "creation_date": "Fecha de creación",
    "modification_date": "Fecha de modificación",
    "file_extension": "Extensión de archivo",
    "creation_time": "Hora de creación:",
    "sorted_by": "Ordenado por:",
    "excel_success": "Archivo Excel creado con éxito",
    "word_success": "Documento Word creado con éxito",
    "html_success": "Archivo HTML creado con éxito",
    "text_success": "Archivo de texto creado con éxito",
    "open_file_title": "Abrir archivo",
    "open_file_message": "¿Desea abrir el archivo?",
    "yes": "Sí",
    "no": "No",
    "tooltip_subfolders": "También lista archivos en subcarpetas",
    "tooltip_format": "Seleccione el formato en el que se guardará su lista",
    "tooltip_save_location": "Seleccione dónde se guardará su lista",
    "tooltip_sort_criteria": "Seleccione cómo se ordenarán los archivos",
    "tooltip_select_all": "Seleccionar todas las extensiones de archivo",
    "tooltip_clear_all": "Borrar todas las selecciones de extensión de archivo",
    "tooltip_file_category": "Haga clic para ver las categorías de archivo",
    "tooltip_file_extension": "Seleccione las extensiones de archivo para listar",
    "tooltip_filter_apply": "Haga clic para aplicar los filtros seleccionados",
    "tooltip_all_files": "Seleccionar/Deseleccionar todas las extensiones de archivo",
    "tooltip_category_expand": "Haga clic para expandir/contraer esta categoría",
    "tooltip_select_category": "Seleccionar/Deseleccionar todas las extensiones en esta categoría",
    "select_all_category": "Seleccionar todas en esta categoría",
    "media_files": "Archivos multimedia (Audio y Video)",
    "code_files": "Archivos de código y web",
    "design_files": "Archivos de diseño",
    "game_files": "Archivos de juegos",
    "extension_search": "Buscar:",
    "cancelling": "⏹️ Cancelando...",
    "view_mode_list": "Lista",
    "view_mode_preview": "Vista previa",
    "tooltip_list_view": "Mostrar archivos en vista de lista",
    "tooltip_preview_view": "Mostrar archivos con miniaturas de vista previa",
    "search_files": "Buscar archivos...",
    "preview_mode_active": "Modo de vista previa activo",
    "loading_preview": "Cargando vistas previas...",
    "no_preview_available": "No se encontraron archivos con vista previa",
    "preview_file": "Vista previa del archivo",
    "prev_page": "Anterior",
    "next_page": "Siguiente",
    "page": "Página",
    "files_and_previews": "Archivos y vistas previas",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}

# Italian language dictionary
it_dict = {
    "open_file": "Apri file",
    "open_file_location": "Apri posizione file",
    "select_folder": "📁 Seleziona cartella",
    "no_folder_selected": "Nessuna cartella selezionata",
    "start": "▶️ Avvia",
    "apply_filter": "🔍 Applica filtro",
    "cancel": "⏹️ Annulla",
    "exit": "✖️ Esci",
    "select_all": "Seleziona tutto",
    "clear_all": "Cancella tutto",
    "all_files_tip": "Tutti i file verranno elencati indipendentemente dall'estensione.",
    "filter_tip": "Opzioni di filtro abilitate, verranno mostrati solo i file con le estensioni selezionate.",
    "calculating_statistics": "Calcolo delle statistiche...",
    "loading_file_list": "Caricamento elenco file...",
    "tooltip_select": "Seleziona una cartella per generare l'elenco dei file",
    "tooltip_start": "Crea ed esporta l'elenco dei file",
    "tooltip_apply": "Filtra i file per estensioni selezionate",
    "tooltip_cancel": "Annulla l'operazione in corso",
    "tooltip_exit": "Esci dall'applicazione",
    "language": "Lingua / Language",
    "settings": "Impostazioni",
    "info": "Informazioni",
    "files_filtering": "Filtraggio dei file, attendere prego...",
    "files_gathering": "Raccolta dei file, attendere prego...",
    "files_loading": "Caricamento file...",
    "filter_applying": "Applicazione filtro...",
    "filter_cancelled": "Operazione di filtraggio annullata",
    "excel_created": "File Excel creato con successo...",
    "error_occurred": "Si è verificato un errore: {0}",
    "error": "Errore",
    "ready": "Pronto",
    "operation_cancelled": "Operazione annullata",
    "file_processed": "Elaborazione file: {0}/{1} • {2}",
    "processing": "Elaborazione: %{0:.1f}",
    "folder_loading": "Caricamento cartella...",
    "loading_subfolders": "Caricamento sottocartelle...",
    "folder_loaded_status": "📁 Contenuto della cartella caricato. Fare clic su \"Avvia\" per creare l'elenco.",
    "create_list_time": "🕒 Orario creazione elenco: {0}",
    "select_folder_first": "Seleziona prima una cartella!",
    "text_file_error": "Impossibile creare il file di testo: {0}",
    "start_processing": "▶️ Creazione elenco...",
    "confirm_exit_title": "Uscita",
    "confirm_exit_message": "Sei sicuro di voler uscire dal programma?",
    "no_files_found": "Nessun file trovato nella cartella selezionata.",
    "files_loaded_message": "{0} file caricati.",
    "files_filtered_message": "{0} file filtrati.",
    "filter_saved_message": "Impostazioni filtro salvate. Verranno applicate quando si seleziona una cartella.",
    "app_title": "ListaFacile - Generatore di elenchi file",
    "app_subtitle": "Elenca rapidamente i file nelle tue cartelle.",
    "full_window_title": "ListaFacile - Generatore di elenchi file",
    "statistics_header": "Statistiche",
    "total_files_label": "Totale file:",
    "folder_count_label": "Numero cartelle:",
    "total_size_label": "Dimensione totale:",
    "tips_header": "Suggerimenti",
    "settings_header": "Impostazioni",
    "operation_status": "Stato operazione",
    "subfolders_label": "Includi sottocartelle:",
    "include_label": "Includi",
    "list_format_label": "Formato elenco:",
    "save_location_label": "Posizione salvataggio:",
    "desktop_label": "Desktop",
    "sort_criteria_label": "Criterio ordinamento:",
    "text_format_info": "Formato file di testo",
    "excel_format_info": "Formato cartella di lavoro Excel",
    "word_format_info": "Formato documento Word",
    "html_format_info": "Formato pagina web",
    "filter_label": "Filtro",
    "kategori_header": "Categorie",
    "extensions_header": "Estensioni file",
    "tip_1": "Seleziona la casella per le sottocartelle.",
    "tip_2": "Seleziona il formato di output.",
    "tip_3": "Puoi ordinare i file.",
    "tip_4": "Gli elenchi vengono salvati nella cartella del programma.",
    "tip_5": "Salva sul desktop con l'opzione desktop.",
    "tip_6": "Usa il pulsante Annulla per interrompere il processo.",
    "all_files": "Tutti i file",
    "image_files": "File immagine",
    "audio_files": "File audio",
    "video_files": "File video",
    "text_files": "File di testo",
    "program_files": "File programma",
    "compressed_files": "File compressi",
    "document_files": "Documenti",
    "spreadsheet_files": "Fogli di calcolo",
    "presentation_files": "Presentazioni",
    "sort_name_asc": "Nome file - Crescente",
    "sort_name_desc": "Nome file - Decrescente",
    "sort_ext_asc": "Estensione file - Crescente",
    "sort_ext_desc": "Estensione file - Decrescente",
    "sort_size_asc": "Dimensione file - Crescente",
    "sort_size_desc": "Dimensione file - Decrescente",
    "sort_dir_asc": "Directory file - Crescente",
    "selected_folder": "Cartella selezionata:",
    "file_list": "Elenco file",
    "row_number": "N. riga",
    "file_name": "Nome file",
    "file_type": "Tipo file",
    "file_path": "Percorso file",
    "file_size": "Dimensione file",
    "creation_date": "Data creazione",
    "modification_date": "Data modifica",
    "file_extension": "Estensione file",
    "creation_time": "Ora creazione:",
    "sorted_by": "Ordinato per:",
    "excel_success": "File Excel creato con successo",
    "word_success": "Documento Word creato con successo",
    "html_success": "File HTML creato con successo",
    "text_success": "File di testo creato con successo",
    "open_file_title": "Apri file",
    "open_file_message": "Vuoi aprire il file?",
    "yes": "Sì",
    "no": "No",
    "tooltip_subfolders": "Elenca anche i file nelle sottocartelle",
    "tooltip_format": "Seleziona il formato in cui verrà salvato il tuo elenco",
    "tooltip_save_location": "Seleziona dove verrà salvato il tuo elenco",
    "tooltip_sort_criteria": "Seleziona come verranno ordinati i file",
    "tooltip_select_all": "Seleziona tutte le estensioni file",
    "tooltip_clear_all": "Cancella tutte le selezioni di estensione file",
    "tooltip_file_category": "Clicca per vedere le categorie di file",
    "tooltip_file_extension": "Seleziona le estensioni file da elencare",
    "tooltip_filter_apply": "Clicca per applicare i filtri selezionati",
    "tooltip_all_files": "Seleziona/Deseleziona tutte le estensioni file",
    "tooltip_category_expand": "Clicca per espandere/comprimere questa categoria",
    "tooltip_select_category": "Seleziona/Deseleziona tutte le estensioni in questa categoria",
    "select_all_category": "Seleziona tutto in questa categoria",
    "media_files": "File multimediali (Audio e Video)",
    "code_files": "File di codice e web",
    "design_files": "File di design",
    "game_files": "File di gioco",
    "extension_search": "Cerca:",
    "cancelling": "⏹️ Annullamento in corso...",
    "view_mode_list": "Elenco",
    "view_mode_preview": "Anteprima",
    "tooltip_list_view": "Mostra file in visualizzazione elenco",
    "tooltip_preview_view": "Mostra file con miniature di anteprima",
    "search_files": "Cerca file...",
    "preview_mode_active": "Modalità anteprima attiva",
    "loading_preview": "Caricamento anteprime...",
    "no_preview_available": "Nessun file con anteprima trovato",
    "preview_file": "Anteprima file",
    "prev_page": "Precedente",
    "next_page": "Successiva",
    "page": "Pagina",
    "files_and_previews": "File e anteprime",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}

# Persian language dictionary
fa_dict = {
    "open_file": "باز کردن فایل",
    "open_file_location": "باز کردن محل فایل",
    "select_folder": "📁 انتخاب پوشه",
    "no_folder_selected": "هنوز پوشه‌ای انتخاب نشده است",
    "start": "▶️ شروع",
    "apply_filter": "🔍 اعمال فیلتر",
    "cancel": "⏹️ لغو",
    "exit": "✖️ خروج",
    "select_all": "انتخاب همه",
    "clear_all": "پاک کردن همه",
    "all_files_tip": "همه فایل‌ها بدون توجه به پسوند فهرست می‌شوند.",
    "filter_tip": "گزینه‌های فیلتر فعال هستند، فقط فایل‌های با پسوندهای انتخاب شده نمایش داده می‌شوند.",
    "calculating_statistics": "در حال محاسبه آمار...",
    "loading_file_list": "در حال بارگذاری لیست فایل‌ها...",
    "tooltip_select": "یک پوشه برای ایجاد لیست فایل انتخاب کنید",
    "tooltip_start": "ایجاد و خروجی گرفتن از لیست فایل",
    "tooltip_apply": "فیلتر کردن فایل‌ها براساس پسوندهای انتخاب شده",
    "tooltip_cancel": "لغو عملیات در حال انجام",
    "tooltip_exit": "خروج از برنامه",
    "language": "زبان / Language",
    "settings": "تنظیمات",
    "info": "اطلاعات",
    "files_filtering": "در حال فیلتر کردن فایل‌ها، لطفاً صبر کنید...",
    "files_gathering": "در حال جمع‌آوری فایل‌ها، لطفاً صبر کنید...",
    "files_loading": "در حال بارگذاری فایل‌ها...",
    "filter_applying": "در حال اعمال فیلتر...",
    "filter_cancelled": "عملیات فیلتر لغو شد",
    "excel_created": "فایل اکسل با موفقیت ایجاد شد...",
    "error_occurred": "خطایی رخ داد: {0}",
    "error": "خطا",
    "ready": "آماده",
    "operation_cancelled": "عملیات لغو شد",
    "file_processed": "در حال پردازش فایل: {0}/{1} • {2}",
    "processing": "در حال پردازش: %{0:.1f}",
    "folder_loading": "در حال بارگذاری پوشه...",
    "loading_subfolders": "در حال بارگذاری زیرپوشه‌ها...",
    "folder_loaded_status": "📁 محتوای پوشه بارگذاری شد. برای ایجاد لیست، روی \"شروع\" کلیک کنید.",
    "create_list_time": "🕒 زمان ایجاد لیست: {0}",
    "select_folder_first": "لطفاً ابتدا یک پوشه انتخاب کنید!",
    "text_file_error": "فایل متنی نمی‌تواند ایجاد شود: {0}",
    "start_processing": "▶️ در حال ایجاد لیست...",
    "confirm_exit_title": "خروج",
    "confirm_exit_message": "آیا مطمئن هستید که می‌خواهید از برنامه خارج شوید؟",
    "no_files_found": "هیچ فایلی در پوشه انتخاب شده یافت نشد.",
    "files_loaded_message": "{0} فایل بارگذاری شد.",
    "files_filtered_message": "{0} فایل فیلتر شد.",
    "filter_saved_message": "تنظیمات فیلتر ذخیره شد. هنگام انتخاب پوشه اعمال خواهد شد.",
    "app_title": "لیست‌آسان - تولیدکننده لیست فایل",
    "app_subtitle": "به سرعت فایل‌های پوشه‌های خود را فهرست کنید.",
    "full_window_title": "لیست‌آسان - تولیدکننده لیست فایل",
    "statistics_header": "آمار",
    "total_files_label": "کل فایل‌ها:",
    "folder_count_label": "تعداد پوشه‌ها:",
    "total_size_label": "اندازه کل:",
    "tips_header": "نکات",
    "settings_header": "تنظیمات",
    "operation_status": "وضعیت عملیات",
    "subfolders_label": "شامل زیرپوشه‌ها:",
    "include_label": "شامل",
    "list_format_label": "قالب لیست:",
    "save_location_label": "محل ذخیره:",
    "desktop_label": "دسکتاپ",
    "sort_criteria_label": "معیار مرتب‌سازی:",
    "text_format_info": "قالب فایل متنی",
    "excel_format_info": "قالب کتاب کاری اکسل",
    "word_format_info": "قالب سند ورد",
    "html_format_info": "قالب صفحه وب",
    "filter_label": "فیلتر",
    "kategori_header": "دسته‌بندی‌ها",
    "extensions_header": "پسوندهای فایل",
    "tip_1": "کادر انتخاب را برای زیرپوشه‌ها فعال کنید.",
    "tip_2": "قالب خروجی را انتخاب کنید.",
    "tip_3": "می‌توانید فایل‌ها را مرتب کنید.",
    "tip_4": "لیست‌ها در پوشه برنامه ذخیره می‌شوند.",
    "tip_5": "با گزینه دسکتاپ در دسکتاپ ذخیره کنید.",
    "tip_6": "از دکمه لغو برای توقف فرآیند استفاده کنید.",
    "all_files": "همه فایل‌ها",
    "image_files": "فایل‌های تصویری",
    "audio_files": "فایل‌های صوتی",
    "video_files": "فایل‌های ویدیویی",
    "text_files": "فایل‌های متنی",
    "program_files": "فایل‌های برنامه",
    "compressed_files": "فایل‌های فشرده",
    "document_files": "اسناد",
    "spreadsheet_files": "صفحات گسترده",
    "presentation_files": "ارائه‌ها",
    "sort_name_asc": "نام فایل - صعودی",
    "sort_name_desc": "نام فایل - نزولی",
    "sort_ext_asc": "پسوند فایل - صعودی",
    "sort_ext_desc": "پسوند فایل - نزولی",
    "sort_size_asc": "اندازه فایل - صعودی",
    "sort_size_desc": "اندازه فایل - نزولی",
    "sort_dir_asc": "مسیر فایل - صعودی",
    "selected_folder": "پوشه انتخاب شده:",
    "file_list": "لیست فایل",
    "row_number": "شماره ردیف",
    "file_name": "نام فایل",
    "file_type": "نوع فایل",
    "file_path": "مسیر فایل",
    "file_size": "اندازه فایل",
    "creation_date": "تاریخ ایجاد",
    "modification_date": "تاریخ تغییر",
    "file_extension": "پسوند فایل",
    "creation_time": "زمان ایجاد:",
    "sorted_by": "مرتب‌شده براساس:",
    "excel_success": "فایل اکسل با موفقیت ایجاد شد",
    "word_success": "سند ورد با موفقیت ایجاد شد",
    "html_success": "فایل HTML با موفقیت ایجاد شد",
    "text_success": "فایل متنی با موفقیت ایجاد شد",
    "open_file_title": "باز کردن فایل",
    "open_file_message": "آیا می‌خواهید فایل را باز کنید؟",
    "yes": "بله",
    "no": "خیر",
    "tooltip_subfolders": "فایل‌های موجود در زیرپوشه‌ها را نیز فهرست می‌کند",
    "tooltip_format": "قالبی را که لیست شما در آن ذخیره می‌شود انتخاب کنید",
    "tooltip_save_location": "انتخاب کنید که لیست شما کجا ذخیره شود",
    "tooltip_sort_criteria": "انتخاب کنید که فایل‌ها چگونه مرتب شوند",
    "tooltip_select_all": "انتخاب همه پسوندهای فایل",
    "tooltip_clear_all": "پاک کردن همه انتخاب‌های پسوند فایل",
    "tooltip_file_category": "برای مشاهده دسته‌بندی‌های فایل کلیک کنید",
    "tooltip_file_extension": "پسوندهای فایل برای فهرست کردن را انتخاب کنید",
    "tooltip_filter_apply": "برای اعمال فیلترهای انتخاب شده کلیک کنید",
    "tooltip_all_files": "انتخاب/لغو انتخاب همه پسوندهای فایل",
    "tooltip_category_expand": "برای گسترش/جمع کردن این دسته کلیک کنید",
    "tooltip_select_category": "انتخاب/لغو انتخاب همه پسوندها در این دسته",
    "select_all_category": "انتخاب همه در این دسته",
    "media_files": "فایل‌های رسانه‌ای (صوتی و تصویری)",
    "code_files": "فایل‌های کد و وب",
    "design_files": "فایل‌های طراحی",
    "game_files": "فایل‌های بازی",
    "extension_search": "جستجو:",
    "cancelling": "⏹️ در حال لغو...",
    "view_mode_list": "لیست",
    "view_mode_preview": "پیش‌نمایش",
    "tooltip_list_view": "نمایش فایل‌ها در حالت لیست",
    "tooltip_preview_view": "نمایش فایل‌ها با تصاویر بندانگشتی پیش‌نمایش",
    "search_files": "جستجوی فایل‌ها...",
    "preview_mode_active": "حالت پیش‌نمایش فعال است",
    "loading_preview": "در حال بارگذاری پیش‌نمایش‌ها...",
    "no_preview_available": "هیچ فایل قابل پیش‌نمایشی یافت نشد",
    "preview_file": "پیش‌نمایش فایل",
    "prev_page": "قبلی",
    "next_page": "بعدی",
    "page": "صفحه",
    "files_and_previews": "فایل‌ها و پیش‌نمایش‌ها",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}

# Urdu language dictionary
ur_dict = {
    "open_file": "فائل کھولیں",
    "open_file_location": "فائل کا مقام کھولیں",
    "select_folder": "📁 فولڈر منتخب کریں",
    "no_folder_selected": "ابھی تک کوئی فولڈر منتخب نہیں کیا گیا",
    "start": "▶️ شروع کریں",
    "apply_filter": "🔍 فلٹر لگائیں",
    "cancel": "⏹️ منسوخ کریں",
    "exit": "✖️ بند کریں",
    "select_all": "سب منتخب کریں",
    "clear_all": "سب صاف کریں",
    "all_files_tip": "تمام فائلیں ایکسٹینشن سے قطع نظر فہرست کی جائیں گی۔",
    "filter_tip": "فلٹر کے اختیارات فعال، صرف منتخب ایکسٹینشن والی فائلیں دکھائی جائیں گی۔",
    "calculating_statistics": "اعداد و شمار کا حساب لگایا جا رہا ہے...",
    "loading_file_list": "فائل کی فہرست لوڈ ہو رہی ہے...",
    "tooltip_select": "فائل کی فہرست بنانے کے لیے فولڈر منتخب کریں",
    "tooltip_start": "فائل کی فہرست بنائیں اور برآمد کریں",
    "tooltip_apply": "منتخب ایکسٹینشن کے مطابق فائلوں کو فلٹر کریں",
    "tooltip_cancel": "جاری آپریشن منسوخ کریں",
    "tooltip_exit": "ایپلیکیشن بند کریں",
    "language": "زبان / Language",
    "settings": "ترتیبات",
    "info": "معلومات",
    "files_filtering": "فائلوں کو فلٹر کیا جا رہا ہے، براہ کرم انتظار کریں...",
    "files_gathering": "فائلیں جمع کی جا رہی ہیں، براہ کرم انتظار کریں...",
    "files_loading": "فائلیں لوڈ ہو رہی ہیں...",
    "filter_applying": "فلٹر لاگو کیا جا رہا ہے...",
    "filter_cancelled": "فلٹر آپریشن منسوخ کر دیا گیا",
    "excel_created": "ایکسل فائل کامیابی سے بنائی گئی...",
    "error_occurred": "ایک خرابی پیش آئی: {0}",
    "error": "خرابی",
    "ready": "تیار",
    "operation_cancelled": "آپریشن منسوخ کر دیا گیا",
    "file_processed": "فائل پر کام ہو رہا ہے: {0}/{1} • {2}",
    "processing": "پروسیسنگ: %{0:.1f}",
    "folder_loading": "فولڈر لوڈ ہو رہا ہے...",
    "loading_subfolders": "ذیلی فولڈرز لوڈ ہو رہے ہیں...",
    "folder_loaded_status": "📁 فولڈر مواد لوڈ ہو گیا ہے۔ فہرست بنانے کے لیے \"شروع کریں\" بٹن پر کلک کریں۔",
    "create_list_time": "🕒 فہرست بنانے کا وقت: {0}",
    "select_folder_first": "براہ کرم پہلے ایک فولڈر منتخب کریں!",
    "text_file_error": "ٹیکسٹ فائل نہیں بنائی جا سکی: {0}",
    "start_processing": "▶️ فہرست بنائی جا رہی ہے...",
    "confirm_exit_title": "بند کریں",
    "confirm_exit_message": "کیا آپ واقعی پروگرام سے باہر نکلنا چاہتے ہیں؟",
    "no_files_found": "منتخب فولڈر میں کوئی فائل نہیں ملی۔",
    "files_loaded_message": "{0} فائلیں لوڈ ہو گئیں۔",
    "files_filtered_message": "{0} فائلیں فلٹر کی گئیں۔",
    "filter_saved_message": "فلٹر کی ترتیبات محفوظ ہو گئیں۔ فولڈر منتخب کرنے پر لاگو ہوں گی۔",
    "app_title": "آسان فہرست - فائل فہرست بنانے والا",
    "app_subtitle": "اپنے فولڈرز میں فائلوں کی فہرست تیزی سے بنائیں۔",
    "full_window_title": "آسان فہرست - فائل فہرست بنانے والا",
    "statistics_header": "اعداد و شمار",
    "total_files_label": "کل فائلیں:",
    "folder_count_label": "فولڈرز کی تعداد:",
    "total_size_label": "کل سائز:",
    "tips_header": "ٹپس",
    "settings_header": "ترتیبات",
    "operation_status": "آپریشن کی حالت",
    "subfolders_label": "ذیلی فولڈرز شامل کریں:",
    "include_label": "شامل کریں",
    "list_format_label": "فہرست کا فارمیٹ:",
    "save_location_label": "محفوظ کرنے کا مقام:",
    "desktop_label": "ڈیسک ٹاپ",
    "sort_criteria_label": "ترتیب کا معیار:",
    "text_format_info": "ٹیکسٹ فائل فارمیٹ",
    "excel_format_info": "ایکسل ورک بک فارمیٹ",
    "word_format_info": "ورڈ دستاویز فارمیٹ",
    "html_format_info": "ویب پیج فارمیٹ",
    "filter_label": "فلٹر",
    "kategori_header": "زمرے",
    "extensions_header": "فائل ایکسٹینشنز",
    "tip_1": "ذیلی فولڈرز کے لیے چیک باکس کو نشان زد کریں۔",
    "tip_2": "آؤٹ پٹ فارمیٹ منتخب کریں۔",
    "tip_3": "آپ فائلوں کو ترتیب دے سکتے ہیں۔",
    "tip_4": "فہرستیں پروگرام فولڈر میں محفوظ کی جاتی ہیں۔",
    "tip_5": "ڈیسک ٹاپ آپشن کے ساتھ ڈیسک ٹاپ پر محفوظ کریں۔",
    "tip_6": "عمل کو روکنے کے لیے منسوخ بٹن استعمال کریں۔",
    "all_files": "تمام فائلیں",
    "image_files": "تصویری فائلیں",
    "audio_files": "آڈیو فائلیں",
    "video_files": "ویڈیو فائلیں",
    "text_files": "ٹیکسٹ فائلیں",
    "program_files": "پروگرام فائلیں",
    "compressed_files": "کمپریسڈ فائلیں",
    "document_files": "دستاویزات",
    "spreadsheet_files": "اسپریڈ شیٹس",
    "presentation_files": "پریزنٹیشنز",
    "sort_name_asc": "فائل نام - چڑھتے ہوئے",
    "sort_name_desc": "فائل نام - اترتے ہوئے",
    "sort_ext_asc": "فائل ایکسٹینشن - چڑھتے ہوئے",
    "sort_ext_desc": "فائل ایکسٹینشن - اترتے ہوئے",
    "sort_size_asc": "فائل سائز - چڑھتے ہوئے",
    "sort_size_desc": "فائل سائز - اترتے ہوئے",
    "sort_dir_asc": "فائل ڈائریکٹری - چڑھتے ہوئے",
    "selected_folder": "منتخب شدہ فولڈر:",
    "file_list": "فائل کی فہرست",
    "row_number": "قطار نمبر",
    "file_name": "فائل کا نام",
    "file_type": "فائل کی قسم",
    "file_path": "فائل کا راستہ",
    "file_size": "فائل کا سائز",
    "creation_date": "تخلیق کی تاریخ",
    "modification_date": "ترمیم کی تاریخ",
    "file_extension": "فائل ایکسٹینشن",
    "creation_time": "تخلیق کا وقت:",
    "sorted_by": "ترتیب کا معیار:",
    "excel_success": "ایکسل فائل کامیابی سے بنائی گئی",
    "word_success": "ورڈ دستاویز کامیابی سے بنائی گئی",
    "html_success": "HTML فائل کامیابی سے بنائی گئی",
    "text_success": "ٹیکسٹ فائل کامیابی سے بنائی گئی",
    "open_file_title": "فائل کھولیں",
    "open_file_message": "کیا آپ فائل کھولنا چاہتے ہیں؟",
    "yes": "ہاں",
    "no": "نہیں",
    "tooltip_subfolders": "ذیلی فولڈرز میں فائلوں کو بھی فہرست کرتا ہے",
    "tooltip_format": "منتخب کریں کہ آپ کی فہرست کس فارمیٹ میں محفوظ ہوگی",
    "tooltip_save_location": "منتخب کریں کہ آپ کی فہرست کہاں محفوظ ہوگی",
    "tooltip_sort_criteria": "منتخب کریں کہ فائلیں کیسے ترتیب دی جائیں گی",
    "tooltip_select_all": "تمام فائل ایکسٹینشنز منتخب کریں",
    "tooltip_clear_all": "تمام فائل ایکسٹینشن انتخابات صاف کریں",
    "tooltip_file_category": "فائل زمرے دیکھنے کے لیے کلک کریں",
    "tooltip_file_extension": "فہرست میں شامل کرنے کے لیے فائل ایکسٹینشنز منتخب کریں",
    "tooltip_filter_apply": "منتخب فلٹرز لاگو کرنے کے لیے کلک کریں",
    "tooltip_all_files": "تمام فائل ایکسٹینشنز منتخب/غیر منتخب کریں",
    "tooltip_category_expand": "اس زمرے کو کھولنے/بند کرنے کے لیے کلک کریں",
    "tooltip_select_category": "اس زمرے میں تمام ایکسٹینشنز منتخب/غیر منتخب کریں",
    "select_all_category": "اس زمرے میں سب منتخب کریں",
    "media_files": "میڈیا فائلیں (آڈیو و ویڈیو)",
    "code_files": "کوڈ اور ویب فائلیں",
    "design_files": "ڈیزائن فائلیں",
    "game_files": "گیم فائلیں",
    "extension_search": "تلاش کریں:",
    "cancelling": "⏹️ منسوخ کیا جا رہا ہے...",
    "view_mode_list": "فہرست نظارہ",
    "view_mode_preview": "پیش نظارہ",
    "tooltip_list_view": "فائلوں کو فہرست کے نظارے میں دکھائیں",
    "tooltip_preview_view": "فائلوں کو تھمب نیل پیش نظارے کے ساتھ دکھائیں",
    "search_files": "فائلیں تلاش کریں...",
    "preview_mode_active": "پیش نظارہ موڈ فعال ہے",
    "loading_preview": "پیش نظارے لوڈ ہو رہے ہیں...",
    "no_preview_available": "کوئی قابل پیش نظارہ فائل نہیں ملی",
    "preview_file": "فائل کا پیش نظارہ",
    "prev_page": "پچھلا",
    "next_page": "اگلا",
    "page": "صفحہ",
    "files_and_previews": "فائلیں اور پیش نظارے",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}

# Hindi language dictionary
hi_dict = {
    "open_file": "फ़ाइल खोलें",
    "open_file_location": "फ़ाइल स्थान खोलें",
    "select_folder": "📁 फ़ोल्डर चुनें",
    "no_folder_selected": "अभी तक कोई फ़ोल्डर नहीं चुना गया है",
    "start": "▶️ शुरू करें",
    "apply_filter": "🔍 फिल्टर लागू करें",
    "cancel": "⏹️ रद्द करें",
    "exit": "✖️ बाहर निकलें",
    "select_all": "सभी चुनें",
    "clear_all": "सभी हटाएँ",
    "all_files_tip": "सभी फ़ाइलें एक्सटेंशन की परवाह किए बिना सूचीबद्ध होंगी।",
    "filter_tip": "फिल्टर विकल्प सक्रिय हैं, केवल चयनित एक्सटेंशन वाली फ़ाइलें दिखाई जाएंगी।",
    "calculating_statistics": "आँकड़े की गणना हो रही है...",
    "loading_file_list": "फ़ाइल सूची लोड हो रही है...",
    "tooltip_select": "फ़ाइल सूची बनाने के लिए एक फ़ोल्डर चुनें",
    "tooltip_start": "फ़ाइल सूची बनाएं और निर्यात करें",
    "tooltip_apply": "चयनित एक्सटेंशन के अनुसार फ़ाइलों को फ़िल्टर करें",
    "tooltip_cancel": "चल रहे ऑपरेशन को रद्द करें",
    "tooltip_exit": "एप्लिकेशन से बाहर निकलें",
    "language": "भाषा / Language",
    "settings": "सेटिंग्स",
    "info": "जानकारी",
    "files_filtering": "फ़ाइलों को फ़िल्टर किया जा रहा है, कृपया प्रतीक्षा करें...",
    "files_gathering": "फ़ाइलों को इकट्ठा किया जा रहा है, कृपया प्रतीक्षा करें...",
    "files_loading": "फ़ाइलें लोड हो रही हैं...",
    "filter_applying": "फिल्टर लागू हो रहा है...",
    "filter_cancelled": "फ़िल्टरिंग ऑपरेशन रद्द किया गया",
    "excel_created": "एक्सेल फ़ाइल सफलतापूर्वक बनाई गई...",
    "error_occurred": "एक त्रुटि हुई: {0}",
    "error": "त्रुटि",
    "ready": "तैयार",
    "operation_cancelled": "ऑपरेशन रद्द किया गया",
    "file_processed": "फ़ाइल प्रोसेस हो रही है: {0}/{1} • {2}",
    "processing": "प्रोसेसिंग: %{0:.1f}",
    "folder_loading": "फ़ोल्डर लोड हो रहा है...",
    "loading_subfolders": "सबफ़ोल्डर्स लोड हो रहे हैं...",
    "folder_loaded_status": "📁 फ़ोल्डर सामग्री लोड हो गई है। सूची बनाने के लिए \"शुरू करें\" बटन पर क्लिक करें।",
    "create_list_time": "🕒 सूची निर्माण का समय: {0}",
    "select_folder_first": "कृपया पहले एक फ़ोल्डर चुनें!",
    "text_file_error": "टेक्स्ट फ़ाइल नहीं बनाई जा सकी: {0}",
    "start_processing": "▶️ सूची बनाई जा रही है...",
    "confirm_exit_title": "बाहर निकलें",
    "confirm_exit_message": "क्या आप वाकई प्रोग्राम से बाहर निकलना चाहते हैं?",
    "no_files_found": "चयनित फ़ोल्डर में कोई फ़ाइल नहीं मिली।",
    "files_loaded_message": "{0} फ़ाइलें लोड हुईं।",
    "files_filtered_message": "{0} फ़ाइलें फ़िल्टर की गईं।",
    "filter_saved_message": "फ़िल्टर सेटिंग्स सहेजी गईं। फ़ोल्डर चुनने पर लागू होंगी।",
    "app_title": "सूचीआसान - फ़ाइल सूची जनरेटर",
    "app_subtitle": "अपने फ़ोल्डरों में फ़ाइलों को जल्दी से सूचीबद्ध करें।",
    "full_window_title": "सूचीआसान - फ़ाइल सूची जनरेटर",
    "statistics_header": "आँकड़े",
    "total_files_label": "कुल फ़ाइलें:",
    "folder_count_label": "फ़ोल्डरों की संख्या:",
    "total_size_label": "कुल आकार:",
    "tips_header": "युक्तियाँ",
    "settings_header": "सेटिंग्स",
    "operation_status": "ऑपरेशन स्थिति",
    "subfolders_label": "सबफ़ोल्डर शामिल करें:",
    "include_label": "शामिल करें",
    "list_format_label": "सूची प्रारूप:",
    "save_location_label": "सहेजने का स्थान:",
    "desktop_label": "डेस्कटॉप",
    "sort_criteria_label": "क्रमबद्ध करने का मापदंड:",
    "text_format_info": "टेक्स्ट फ़ाइल प्रारूप",
    "excel_format_info": "एक्सेल वर्कबुक प्रारूप",
    "word_format_info": "वर्ड दस्तावेज़ प्रारूप",
    "html_format_info": "वेब पेज प्रारूप",
    "filter_label": "फिल्टर",
    "kategori_header": "श्रेणियाँ",
    "extensions_header": "फ़ाइल एक्सटेंशन",
    "tip_1": "सबफ़ोल्डर्स के लिए चेकबॉक्स को सक्रिय करें।",
    "tip_2": "आउटपुट प्रारूप चुनें।",
    "tip_3": "आप फ़ाइलों को क्रमबद्ध कर सकते हैं।",
    "tip_4": "सूचियां प्रोग्राम फ़ोल्डर में सहेजी जाती हैं।",
    "tip_5": "डेस्कटॉप विकल्प के साथ डेस्कटॉप पर सहेजें।",
    "tip_6": "प्रक्रिया को रोकने के लिए रद्द बटन का उपयोग करें।",
    "all_files": "सभी फ़ाइलें",
    "image_files": "छवि फ़ाइलें",
    "audio_files": "ऑडियो फ़ाइलें",
    "video_files": "वीडियो फ़ाइलें",
    "text_files": "टेक्स्ट फ़ाइलें",
    "program_files": "प्रोग्राम फ़ाइलें",
    "compressed_files": "संपीड़ित फ़ाइलें",
    "document_files": "दस्तावेज़",
    "spreadsheet_files": "स्प्रेडशीट्स",
    "presentation_files": "प्रस्तुतियाँ",
    "sort_name_asc": "फ़ाइल नाम - आरोही",
    "sort_name_desc": "फ़ाइल नाम - अवरोही",
    "sort_ext_asc": "फ़ाइल एक्सटेंशन - आरोही",
    "sort_ext_desc": "फ़ाइल एक्सटेंशन - अवरोही",
    "sort_size_asc": "फ़ाइल आकार - आरोही",
    "sort_size_desc": "फ़ाइल आकार - अवरोही",
    "sort_dir_asc": "फ़ाइल डायरेक्टरी - आरोही",
    "selected_folder": "चयनित फ़ोल्डर:",
    "file_list": "फ़ाइल सूची",
    "row_number": "क्रम संख्या",
    "file_name": "फ़ाइल का नाम",
    "file_type": "फ़ाइल प्रकार",
    "file_path": "फ़ाइल पथ",
    "file_size": "फ़ाइल का आकार",
    "creation_date": "निर्माण तिथि",
    "modification_date": "संशोधन तिथि",
    "file_extension": "फ़ाइल एक्सटेंशन",
    "creation_time": "निर्माण समय:",
    "sorted_by": "इसके द्वारा क्रमबद्ध:",
    "excel_success": "एक्सेल फ़ाइल सफलतापूर्वक बनाई गई",
    "word_success": "वर्ड दस्तावेज़ सफलतापूर्वक बनाया गया",
    "html_success": "HTML फ़ाइल सफलतापूर्वक बनाई गई",
    "text_success": "टेक्स्ट फ़ाइल सफलतापूर्वक बनाई गई",
    "open_file_title": "फ़ाइल खोलें",
    "open_file_message": "क्या आप फ़ाइल खोलना चाहते हैं?",
    "yes": "हां",
    "no": "नहीं",
    "tooltip_subfolders": "सबफ़ोल्डर्स में फ़ाइलों को भी सूचीबद्ध करता है",
    "tooltip_format": "वह प्रारूप चुनें जिसमें आपकी सूची सहेजी जाएगी",
    "tooltip_save_location": "चुनें कि आपकी सूची कहां सहेजी जाएगी",
    "tooltip_sort_criteria": "चुनें कि फ़ाइलों को कैसे क्रमबद्ध किया जाएगा",
    "tooltip_select_all": "सभी फ़ाइल एक्सटेंशन चुनें",
    "tooltip_clear_all": "सभी फ़ाइल एक्सटेंशन चयन हटाएँ",
    "tooltip_file_category": "फ़ाइल श्रेणियां देखने के लिए क्लिक करें",
    "tooltip_file_extension": "सूचीबद्ध करने के लिए फ़ाइल एक्सटेंशन चुनें",
    "tooltip_filter_apply": "चयनित फ़िल्टर लागू करने के लिए क्लिक करें",
    "tooltip_all_files": "सभी फ़ाइल एक्सटेंशन चुनें/अचयनित करें",
    "tooltip_category_expand": "इस श्रेणी को विस्तृत/संकुचित करने के लिए क्लिक करें",
    "tooltip_select_category": "इस श्रेणी में सभी एक्सटेंशन चुनें/अचयनित करें",
    "select_all_category": "इस श्रेणी में सभी चुनें",
    "media_files": "मीडिया फ़ाइलें (ऑडियो और वीडियो)",
    "code_files": "कोड और वेब फ़ाइलें",
    "design_files": "डिज़ाइन फ़ाइलें",
    "game_files": "गेम फ़ाइलें",
    "extension_search": "खोजें:",
    "cancelling": "⏹️ रद्द हो रहा है...",
    "view_mode_list": "सूची दृश्य",
    "view_mode_preview": "पूर्वावलोकन",
    "tooltip_list_view": "फ़ाइलों को सूची दृश्य में दिखाएँ",
    "tooltip_preview_view": "फ़ाइलों को पूर्वावलोकन थंबनेल के साथ दिखाएँ",
    "search_files": "फ़ाइलें खोजें...",
    "preview_mode_active": "पूर्वावलोकन मोड सक्रिय है",
    "loading_preview": "पूर्वावलोकन लोड हो रहे हैं...",
    "no_preview_available": "कोई पूर्वावलोकन योग्य फ़ाइल नहीं मिली",
    "preview_file": "फ़ाइल का पूर्वावलोकन",
    "prev_page": "पिछला",
    "next_page": "अगला",
    "page": "पृष्ठ",
    "files_and_previews": "फ़ाइलें और पूर्वावलोकन",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}

# Chinese Simplified language dictionary
zh_dict = {
    "open_file": "打开文件",
    "open_file_location": "打开文件位置",
    "select_folder": "📁 选择文件夹",
    "no_folder_selected": "尚未选择文件夹",
    "start": "▶️ 开始",
    "apply_filter": "🔍 应用筛选",
    "cancel": "⏹️ 取消",
    "exit": "✖️ 退出",
    "select_all": "全选",
    "clear_all": "清除全部",
    "all_files_tip": "将列出所有文件，不考虑扩展名。",
    "filter_tip": "筛选选项已启用，只会显示所选扩展名的文件。",
    "calculating_statistics": "正在计算统计信息...",
    "loading_file_list": "正在加载文件列表...",
    "tooltip_select": "选择一个文件夹以生成文件列表",
    "tooltip_start": "创建并导出文件列表",
    "tooltip_apply": "按所选扩展名筛选文件",
    "tooltip_cancel": "取消正在进行的操作",
    "tooltip_exit": "退出应用程序",
    "language": "语言 / Language",
    "settings": "设置",
    "info": "信息",
    "files_filtering": "正在筛选文件，请稍候...",
    "files_gathering": "正在收集文件，请稍候...",
    "files_loading": "正在加载文件...",
    "filter_applying": "正在应用筛选器...",
    "filter_cancelled": "筛选操作已取消",
    "excel_created": "Excel文件创建成功...",
    "error_occurred": "发生错误: {0}",
    "error": "错误",
    "ready": "就绪",
    "operation_cancelled": "操作已取消",
    "file_processed": "正在处理文件: {0}/{1} • {2}",
    "processing": "处理中: %{0:.1f}",
    "folder_loading": "正在加载文件夹...",
    "loading_subfolders": "正在加载子文件夹...",
    "folder_loaded_status": "📁 文件夹内容已加载。点击\"开始\"按钮创建列表。",
    "create_list_time": "🕒 列表创建时间: {0}",
    "select_folder_first": "请先选择一个文件夹！",
    "text_file_error": "无法创建文本文件: {0}",
    "start_processing": "▶️ 正在创建列表...",
    "confirm_exit_title": "退出",
    "confirm_exit_message": "您确定要退出程序吗？",
    "no_files_found": "在所选文件夹中未找到文件。",
    "files_loaded_message": "已加载 {0} 个文件。",
    "files_filtered_message": "已筛选 {0} 个文件。",
    "filter_saved_message": "筛选设置已保存。选择文件夹时将应用。",
    "app_title": "轻松列表 - 文件列表生成器",
    "app_subtitle": "快速列出文件夹中的文件。",
    "full_window_title": "轻松列表 - 文件列表生成器",
    "statistics_header": "统计",
    "total_files_label": "文件总数:",
    "folder_count_label": "文件夹数量:",
    "total_size_label": "总大小:",
    "tips_header": "提示",
    "settings_header": "设置",
    "operation_status": "操作状态",
    "subfolders_label": "包含子文件夹:",
    "include_label": "包含",
    "list_format_label": "列表格式:",
    "save_location_label": "保存位置:",
    "desktop_label": "桌面",
    "sort_criteria_label": "排序标准:",
    "text_format_info": "文本文件格式",
    "excel_format_info": "Excel工作簿格式",
    "word_format_info": "Word文档格式",
    "html_format_info": "网页格式",
    "filter_label": "筛选",
    "kategori_header": "类别",
    "extensions_header": "文件扩展名",
    "tip_1": "勾选子文件夹复选框。",
    "tip_2": "选择输出格式。",
    "tip_3": "您可以对文件进行排序。",
    "tip_4": "列表保存在程序文件夹中。",
    "tip_5": "使用桌面选项保存到桌面。",
    "tip_6": "使用取消按钮停止进程。",
    "all_files": "所有文件",
    "image_files": "图像文件",
    "audio_files": "音频文件",
    "video_files": "视频文件",
    "text_files": "文本文件",
    "program_files": "程序文件",
    "compressed_files": "压缩文件",
    "document_files": "文档",
    "spreadsheet_files": "电子表格",
    "presentation_files": "演示文稿",
    "sort_name_asc": "文件名 - 升序",
    "sort_name_desc": "文件名 - 降序",
    "sort_ext_asc": "文件扩展名 - 升序",
    "sort_ext_desc": "文件扩展名 - 降序",
    "sort_size_asc": "文件大小 - 升序",
    "sort_size_desc": "文件大小 - 降序",
    "sort_dir_asc": "文件目录 - 升序",
    "selected_folder": "已选择的文件夹:",
    "file_list": "文件列表",
    "row_number": "行号",
    "file_name": "文件名",
    "file_type": "文件类型",
    "file_path": "文件路径",
    "file_size": "文件大小",
    "creation_date": "创建日期",
    "modification_date": "修改日期",
    "file_extension": "文件扩展名",
    "creation_time": "创建时间:",
    "sorted_by": "排序方式:",
    "excel_success": "Excel文件创建成功",
    "word_success": "Word文档创建成功",
    "html_success": "HTML文件创建成功",
    "text_success": "文本文件创建成功",
    "open_file_title": "打开文件",
    "open_file_message": "您想打开该文件吗？",
    "yes": "是",
    "no": "否",
    "tooltip_subfolders": "也列出子文件夹中的文件",
    "tooltip_format": "选择您的列表将保存的格式",
    "tooltip_save_location": "选择您的列表将保存的位置",
    "tooltip_sort_criteria": "选择文件的排序方式",
    "tooltip_select_all": "选择所有文件扩展名",
    "tooltip_clear_all": "清除所有文件扩展名选择",
    "tooltip_file_category": "点击查看文件类别",
    "tooltip_file_extension": "选择要列出的文件扩展名",
    "tooltip_filter_apply": "点击应用所选筛选器",
    "tooltip_all_files": "选择/取消选择所有文件扩展名",
    "tooltip_category_expand": "点击展开/折叠此类别",
    "tooltip_select_category": "选择/取消选择此类别中的所有扩展名",
    "select_all_category": "选择此类别中的所有项",
    "media_files": "媒体文件（音频和视频）",
    "code_files": "代码和网页文件",
    "design_files": "设计文件",
    "game_files": "游戏文件",
    "extension_search": "搜索:",
    "cancelling": "⏹️ 正在取消...",
    "view_mode_list": "列表视图",
    "view_mode_preview": "预览",
    "tooltip_list_view": "以列表视图显示文件",
    "tooltip_preview_view": "显示带有预览缩略图的文件",
    "search_files": "搜索文件...",
    "preview_mode_active": "预览模式已激活",
    "loading_preview": "正在加载预览...",
    "no_preview_available": "未找到可预览的文件",
    "preview_file": "预览文件",
    "prev_page": "上一页",
    "next_page": "下一页",
    "page": "页面",
    "files_and_previews": "文件和预览",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}

# Japanese language dictionary
ja_dict = {
    "open_file": "ファイルを開く",
    "open_file_location": "ファイルの場所を開く",
    "select_folder": "📁 フォルダを選択",
    "no_folder_selected": "まだフォルダが選択されていません",
    "start": "▶️ 開始",
    "apply_filter": "🔍 フィルターを適用",
    "cancel": "⏹️ キャンセル",
    "exit": "✖️ 終了",
    "select_all": "すべて選択",
    "clear_all": "すべてクリア",
    "all_files_tip": "拡張子に関係なく、すべてのファイルが一覧表示されます。",
    "filter_tip": "フィルターオプションが有効です。選択された拡張子を持つファイルのみが表示されます。",
    "calculating_statistics": "統計を計算中...",
    "loading_file_list": "ファイルリストを読み込み中...",
    "tooltip_select": "ファイルリストを生成するフォルダを選択してください",
    "tooltip_start": "ファイルリストを作成してエクスポートします",
    "tooltip_apply": "選択した拡張子でファイルをフィルタリングします",
    "tooltip_cancel": "進行中の操作をキャンセルします",
    "tooltip_exit": "アプリケーションを終了します",
    "language": "言語 / Language",
    "settings": "設定",
    "info": "情報",
    "files_filtering": "ファイルをフィルタリング中、お待ちください...",
    "files_gathering": "ファイルを収集中、お待ちください...",
    "files_loading": "ファイルを読み込み中...",
    "filter_applying": "フィルターを適用中...",
    "filter_cancelled": "フィルタリング操作がキャンセルされました",
    "excel_created": "Excelファイルが正常に作成されました...",
    "error_occurred": "エラーが発生しました: {0}",
    "error": "エラー",
    "ready": "準備完了",
    "operation_cancelled": "操作がキャンセルされました",
    "file_processed": "ファイル処理中: {0}/{1} • {2}",
    "processing": "処理中: %{0:.1f}",
    "folder_loading": "フォルダを読み込み中...",
    "loading_subfolders": "サブフォルダを読み込み中...",
    "folder_loaded_status": "📁 フォルダコンテンツが読み込まれました。リストを作成するには「開始」ボタンをクリックしてください。",
    "create_list_time": "🕒 リスト作成時間: {0}",
    "select_folder_first": "まずフォルダを選択してください！",
    "text_file_error": "テキストファイルを作成できませんでした: {0}",
    "start_processing": "▶️ リストを作成中...",
    "confirm_exit_title": "終了",
    "confirm_exit_message": "本当にプログラムを終了しますか？",
    "no_files_found": "選択したフォルダにファイルが見つかりません。",
    "files_loaded_message": "{0}ファイルが読み込まれました。",
    "files_filtered_message": "{0}ファイルがフィルタリングされました。",
    "filter_saved_message": "フィルター設定が保存されました。フォルダを選択すると適用されます。",
    "app_title": "簡単リスト - ファイルリストジェネレーター",
    "app_subtitle": "フォルダ内のファイルを素早くリスト化します。",
    "full_window_title": "簡単リスト - ファイルリストジェネレーター",
    "statistics_header": "統計",
    "total_files_label": "総ファイル数:",
    "folder_count_label": "フォルダ数:",
    "total_size_label": "合計サイズ:",
    "tips_header": "ヒント",
    "settings_header": "設定",
    "operation_status": "操作ステータス",
    "subfolders_label": "サブフォルダを含める:",
    "include_label": "含める",
    "list_format_label": "リスト形式:",
    "save_location_label": "保存場所:",
    "desktop_label": "デスクトップ",
    "sort_criteria_label": "並べ替え条件:",
    "text_format_info": "テキストファイル形式",
    "excel_format_info": "Excelブック形式",
    "word_format_info": "Word文書形式",
    "html_format_info": "ウェブページ形式",
    "filter_label": "フィルター",
    "kategori_header": "カテゴリー",
    "extensions_header": "ファイル拡張子",
    "tip_1": "サブフォルダ用のチェックボックスをオンにします。",
    "tip_2": "出力形式を選択します。",
    "tip_3": "ファイルを並べ替えることができます。",
    "tip_4": "リストはプログラムフォルダに保存されます。",
    "tip_5": "デスクトップオプションでデスクトップに保存します。",
    "tip_6": "プロセスを停止するにはキャンセルボタンを使用します。",
    "all_files": "すべてのファイル",
    "image_files": "画像ファイル",
    "audio_files": "音声ファイル",
    "video_files": "動画ファイル",
    "text_files": "テキストファイル",
    "program_files": "プログラムファイル",
    "compressed_files": "圧縮ファイル",
    "document_files": "文書",
    "spreadsheet_files": "スプレッドシート",
    "presentation_files": "プレゼンテーション",
    "sort_name_asc": "ファイル名 - 昇順",
    "sort_name_desc": "ファイル名 - 降順",
    "sort_ext_asc": "ファイル拡張子 - 昇順",
    "sort_ext_desc": "ファイル拡張子 - 降順",
    "sort_size_asc": "ファイルサイズ - 昇順",
    "sort_size_desc": "ファイルサイズ - 降順",
    "sort_dir_asc": "ファイルディレクトリ - 昇順",
    "selected_folder": "選択されたフォルダ:",
    "file_list": "ファイルリスト",
    "row_number": "行番号",
    "file_name": "ファイル名",
    "file_type": "ファイルタイプ",
    "file_path": "ファイルパス",
    "file_size": "ファイルサイズ",
    "creation_date": "作成日",
    "modification_date": "更新日",
    "file_extension": "ファイル拡張子",
    "creation_time": "作成時間:",
    "sorted_by": "並べ替え基準:",
    "excel_success": "Excelファイルが正常に作成されました",
    "word_success": "Word文書が正常に作成されました",
    "html_success": "HTMLファイルが正常に作成されました",
    "text_success": "テキストファイルが正常に作成されました",
    "open_file_title": "ファイルを開く",
    "open_file_message": "ファイルを開きますか？",
    "yes": "はい",
    "no": "いいえ",
    "tooltip_subfolders": "サブフォルダ内のファイルも一覧表示します",
    "tooltip_format": "リストを保存する形式を選択します",
    "tooltip_save_location": "リストを保存する場所を選択します",
    "tooltip_sort_criteria": "ファイルの並べ替え方法を選択します",
    "tooltip_select_all": "すべてのファイル拡張子を選択します",
    "tooltip_clear_all": "すべてのファイル拡張子の選択をクリアします",
    "tooltip_file_category": "ファイルカテゴリを表示するにはクリックします",
    "tooltip_file_extension": "一覧表示するファイル拡張子を選択します",
    "tooltip_filter_apply": "選択したフィルターを適用するにはクリックします",
    "tooltip_all_files": "すべてのファイル拡張子を選択/選択解除します",
    "tooltip_category_expand": "このカテゴリを展開/折りたたむにはクリックします",
    "tooltip_select_category": "このカテゴリ内のすべての拡張子を選択/選択解除します",
    "select_all_category": "このカテゴリ内のすべてを選択",
    "media_files": "メディアファイル (音声と動画)",
    "code_files": "コードとウェブファイル",
    "design_files": "デザインファイル",
    "game_files": "ゲームファイル",
    "extension_search": "検索:",
    "cancelling": "⏹️ キャンセル中...",
    "view_mode_list": "リスト表示",
    "view_mode_preview": "プレビュー",
    "tooltip_list_view": "ファイルをリスト表示で表示します",
    "tooltip_preview_view": "プレビューサムネイル付きでファイルを表示します",
    "search_files": "ファイルを検索...",
    "preview_mode_active": "プレビューモードがアクティブです",
    "loading_preview": "プレビューを読み込み中...",
    "no_preview_available": "プレビュー可能なファイルが見つかりません",
    "preview_file": "ファイルをプレビュー",
    "prev_page": "前へ",
    "next_page": "次へ",
    "page": "ページ",
    "files_and_previews": "ファイルとプレビュー",
    "copyright_footer": "© {year} Muallimun.Net - ListeKolay"
}
